"""cms rate reference tables

Revision ID: 8d65979d8ce8
Revises: a43753d800f5
Create Date: 2026-07-07 02:23:26.837110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d65979d8ce8'
down_revision: Union[str, Sequence[str], None] = 'a43753d800f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpci_values',
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('locality_number', sa.String(length=4), nullable=False),
    sa.Column('locality_name', sa.String(length=255), nullable=False),
    sa.Column('work_gpci', sa.Float(), nullable=False),
    sa.Column('pe_gpci', sa.Float(), nullable=False),
    sa.Column('mp_gpci', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('state', 'locality_number')
    )
    op.create_table('locality_counties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mac', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('locality_number', sa.String(length=4), nullable=False),
    sa.Column('fee_schedule_area', sa.String(length=255), nullable=False),
    sa.Column('counties_raw', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_locality_counties_state', 'locality_counties', ['state'], unique=False)
    op.create_table('rvu_values',
    sa.Column('cpt', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.String(length=4), nullable=False),
    sa.Column('work_rvu', sa.Float(), nullable=False),
    sa.Column('pe_rvu_nonfacility', sa.Float(), nullable=False),
    sa.Column('mp_rvu', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('cpt')
    )
    op.create_table('zip_locality',
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('county', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('locality_number', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('zip_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zip_locality')
    op.drop_table('rvu_values')
    op.drop_index('ix_locality_counties_state', table_name='locality_counties')
    op.drop_table('locality_counties')
    op.drop_table('gpci_values')
    # ### end Alembic commands ###
