"""widen locality_counties state column

Revision ID: 99046c042b17
Revises: 8d65979d8ce8
Create Date: 2026-07-07 02:25:04.707636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99046c042b17'
down_revision: Union[str, Sequence[str], None] = '8d65979d8ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locality_counties', 'state',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locality_counties', 'state',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###
